name: Test

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Build marine-python docker image"
      run: docker build --build-arg MARINE_CORE_TAG=$(echo ${GITHUB_REF##refs/heads/} | tr / -) --pull -t marine-python .

    - name: "Run marine-python tests"
      run: docker run -i --rm  -v $(pwd):/marine-python -v $(pwd)/dist:/io marine-python

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
